### ISSUE TITLE
vet-action action unable to detect API key

### ISSUE THREAD

**Issue by hnanda21** [safedep/vet-action#111]
Hi Team,

Kindly refer to the below config for using Vet Cloud mode:
```
uses: safedep/vet-action@v1
with:
  cloud: true
  cloud-tenant: ${{ inputs.sfd-tenant }}
  cloud-key: ${{ inputs.sfd-token }}
```

Given that inputs are properly injected during the workflow run, we're still getting this error:
> Error: API key is required for cloud mode

Thanks.

CC: @abhisek
